email:
  from: xxx@qq.com
  password: eeee
  server: smtp.qq.com
  port: 25
  to: eee@qq.com

city_code: [21] # 21是上海
tags_selected: [
    '流行',
    '独立',
    '电子',
    '摇滚',
    '爵士',
    # '世界音乐',
    '民谣',
    '朋克',
    '金属',
    '布鲁斯',
    '极端金属',
    '灵魂乐',
    '核',
  ]
db_file: showstart.db
log:
  log_suffix: showstart
  log_dir: logs
